# Generated by Django 3.1.3 on 2020-11-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('document', models.FileField(blank=True, null=True, upload_to='specifications/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
